version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iti_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    container_name: nginx-service
    ports:
      - "8080:80"
    depends_on:
      - mysql
  